service: projects
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:Invoke"
        - "execute-api:ManageConnections"

      Resource:
        - "arn:aws:execute-api:*:*:*"

functions: 
  createSocket:
    name: createSocket-${opt:stage}
    handler: handlers/createSocket/handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default